import Head from 'next/head';

import '../styles/globals.scss';
import 'macro-css';

import { CssBaseline, MuiThemeProvider } from '@material-ui/core';
import { theme } from '../theme';
import { Header}  from '../components/Header';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>tjournal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"></link>
      </Head>
      <MuiThemeProvider theme={theme}>
        <Header />
        <CssBaseline />
        <Component {...pageProps} />
      </MuiThemeProvider>
    </>

  )
}

export default MyApp
